/**
 *AUTOGENERATED, DO NOT EDIT DIRECTLY. 
 */
import { Record } from '@quenk/noni/lib/data/record';

import { FieldSet } from '@quenk/backend/lib/app/model';

import _job from './job';
import _mailMessage from './mail-message';

/**
 * fieldsAvailable from this module.
 */
export const fieldsAvailable: Record<FieldSet> = {


    'job': _job,

    'mailMessage': _mailMessage

}

