/**
 *AUTOGENERATED, DO NOT EDIT DIRECTLY. 
 */
import { Record } from '@quenk/noni/lib/data/record';

import { FieldSet } from '@quenk/backend/lib/app/model';

import _admin from './admin';
import _event from './event';
import _invite from './invite';
import _job from './job';
import _user from './user';

/**
 * fieldsAvailable from this module.
 */
export const fieldsAvailable: Record<FieldSet> = {


    'admin': _admin,

    'event': _event,

    'invite': _invite,

    'job': _job,

    'user': _user

}

