CONVERSE_SCHEMA_DIR?=$(CONVERSE_DIR)/schema
CONVERSE_SCHEMA_TARGETS?=$(foreach name,$(notdir $(basename $(wildcard \
                      $(CONVERSE_SCHEMA_DIR)/*.json))),$(CONVERSE_SCHEMA_DIR)/$(name).json)

CONVERSE_SCHEMA_NAMES?=$(notdir $(basename $(CONVERSE_SCHEMA_TARGETS)))
CONVERSE_SCHEMA_TYPE_NAMES?=login
CONVERSE_SCHEMA_MODEL_NAMES:=$(filter-out $(CONVERSE_SCHEMA_TYPE_NAMES),$(CONVERSE_SCHEMA_NAMES))

CONVERSE_SCHEMA_MODEL_TARGETS:=$(addsuffix .json,$(addprefix $(CONVERSE_SCHEMA_DIR)/,\
			  $(CONVERSE_SCHEMA_MODEL_NAMES)))

CONVERSE_SCHEMA_FILES:=$(addsuffix .json,$(addprefix $(CONVERSE_SCHEMA_DIR)/,\
                  $(CONVERSE_SCHEMA_NAMES)))
