/**
 * AUTOGENERATED DO NOT EDIT DIRECTLY!
 */
import { Record } from '@quenk/noni/lib/data/record';
import { EnabledPolicies } from '@quenk/search-filters-mongodb';
export { EnabledPolicies };
/**
 * policiesAvailable is a map of model names to search filter policies that can
 * be used in an application.
 */
export declare const policiesAvailable: Record<EnabledPolicies>;
