BOARD_VALIDATORS_DIR:=$(BOARD_PACKAGES_DIR)/board-validators
BOARD_VALIDATORS_PLUGIN?=node_modules/@quenk/dagen-commons/lib/plugins/validation
BOARD_VALIDATORS_SRC_DIR:=$(BOARD_VALIDATORS_DIR)/src
BOARD_VALIDATORS_SRC_DIR_FILES:=$(shell find $(BOARD_VALIDATORS_SRC_DIR) -type f)
BOARD_VALIDATORS_LIB_DIR:=$(BOARD_VALIDATORS_DIR)/lib

BOARD_VALIDATORS_TEMPLATE_DIR:=$(BOARD_VALIDATORS_DIR)/templates
BOARD_VALIDATORS_TEMPLATE_DIR_FILES:=$(shell find \
				    $(BOARD_VALIDATORS_TEMPLATE_DIR) -type f)
BOARD_VALIDATORS_TYPE_TEMPLATE:=type.validators
BOARD_VALIDATORS_INDEX_TEMPLATE:=index.validators

BOARD_VALIDATORS_MODEL_FILES=$(wildcard $(BOARD_SCHEMA_MODELS_DIR)/*.json)
BOARD_VALIDATORS_TYPES_FILES=$(wildcard $(BOARD_SCHEMA_TYPES_DIR)/*.json)
BOARD_VALIDATORS_SRC_FILES=$(BOARD_VALIDATORS_MODEL_FILES) \
			  $(BOARD_VALIDATORS_TYPES_FILES)
BOARD_VALIDATORS_SRC_FILES_NAMES=$(notdir $(basename \
				$(BOARD_VALIDATORS_MODEL_FILES)))

# Test generation.
BOARD_VALIDATORS_TEST_DIR:=$(BOARD_VALIDATORS_DIR)/test
BOARD_VALIDATORS_UNIT_TEST_DIR:=$(BOARD_VALIDATORS_TEST_DIR)/unit
BOARD_VALIDATORS_TEST_TEMPLATE:=test.validators
BOARD_VALIDATORS_TEST_DATA_DIR:=$(BOARD_VALIDATORS_TEST_DIR)/fixtures/data 
BOARD_VALIDATORS_EXTRA_TEST_DIR:=$(BOARD_VALIDATORS_TEST_DIR)/unitextras

# Hook into clean task.
CLEAN_TARGETS:=$(CLEAN_TARGETS)\
               $(BOARD_VALIDATORS_LIB_DIR)\
	       $(BOARD_VALIDATORS_TEST_DIR)

# Add our sources to the list of total project sources.
SRC_DIRS:=$(SRC_DIRS)\
	  $(BOARD_VALIDATORS_SRC_DIR)\
	  $(BOARD_VALIDATORS_TEST_DATA_DIR)\
	  $(BOARD_VALIDATORS_TEMPLATE_DIR)
