# Requires:
# 1. CONVERSE_FILTER_POLICIES_DIR
# 2. CONVERSE_SCHEMA_MODELS_DIR

CONVERSE_FILTER_POLICIES_DIR:=$(CONVERSE_PACKAGES_DIR)/converse-filter-policies
CONVERSE_FILTER_POLICIES_LIB_DIR:=$(CONVERSE_FILTER_POLICIES_DIR)/lib
CONVERSE_FILTER_POLICIES_SRC_DIR:=$(CONVERSE_FILTER_POLICIES_DIR)/src
CONVERSE_FILTER_POLICIES_TEMPLATES_DIR:=$(CONVERSE_FILTER_POLICIES_DIR)/templates

CONVERSE_FILTER_POLICIES_TEMPLATE_FILES:=\
                      $(shell find $(CONVERSE_FILTER_POLICIES_TEMPLATES_DIR) -type f)

CONVERSE_FILTER_POLICIES_SRC_DIR_FILES:=\
                      $(shell find $(CONVERSE_FILTER_POLICIES_SRC_DIR) -type f)

CONVERSE_FILTER_POLICIES_MODEL_FILES=$(wildcard $(CONVERSE_SCHEMA_MODELS_DIR)/*.json)

CONVERSE_FIELDS_MODEL_NAMES=$(notdir $(basename $(wildcard \
			   $(CONVERSE_SCHEMA_MODELS_DIR)/*.json)))