CONVERSE_REMOTE_MODELS_DIR:=$(CONVERSE_FRONTEND_SRC_DIR)/app/remote/models
CONVERSE_REMOTE_MODELS_FILES=$(addsuffix .ts,$(addprefix $(CONVERSE_REMOTE_MODELS_DIR)/,\
			$(CONVERSE_SCHEMA_MODEL_NAMES)))
QTL_REMOTE_MODELS_TEMPLATES:=$(CONVERSE_REMOTE_MODELS_DIR)/templates
CLEAN_TARGETS:=$(CLEAN_TARGETS) $(CONVERSE_REMOTE_MODELS_DIR)/*.ts
