DEVCARIB_VIEWS_DIR:=$(PACKAGES_DIR)/devcarib-views
DEVCARIB_VIEWS_JS_VARS:=$(HERE)/node_modules/@quenk/wml-widgets/lib/classNames.js
DEVCARIB_VIEWS_LIB_DIR:=$(DEVCARIB_VIEWS_DIR)/lib
DEVCARIB_VIEWS_SRC_DIR:=$(DEVCARIB_VIEWS_DIR)/src
DEVCARIB_VIEWS_SRC_DIR_FILES:=$(shell find $(DEVCARIB_VIEWS_SRC_DIR) -name \*.wml)
DEVCARIB_VIEWS_PUBLIC_DIR:=$(DEVCARIB_VIEWS_DIR)/public

# mia
DEVCARIB_VIEWS_MIA_LESS_FILES:=$(shell find $(DEVCARIB_VIEWS_SRC_DIR)/mia -name \*.less)
DEVCARIB_VIEWS_MIA_LESS_MAIN:=$(DEVCARIB_VIEWS_SRC_DIR)/mia.less
DEVCARIB_VIEWS_MIA_LESS_IMPORTS:=$(DEVCARIB_VIEWS_SRC_DIR)/mia-auto.less
DEVCARIB_VIEWS_MIA_CSS_FILE:=$(DEVCARIB_VIEWS_PUBLIC_DIR)/mia/assets/css/mia.css

# converse
DEVCARIB_VIEWS_CONVERSE_LESS_FILES:=$(shell find $(DEVCARIB_VIEWS_SRC_DIR)/converse -name \*.less)
DEVCARIB_VIEWS_CONVERSE_LESS_MAIN:=$(DEVCARIB_VIEWS_SRC_DIR)/converse.less
DEVCARIB_VIEWS_CONVERSE_LESS_IMPORTS:=$(DEVCARIB_VIEWS_SRC_DIR)/converse-auto.less
DEVCARIB_VIEWS_CONVERSE_CSS_FILE:=$(DEVCARIB_VIEWS_PUBLIC_DIR)/converse/assets/css/converse.css


CLEAN_TARGETS:=$(CLEAN_TARGETS)\
	       $(DEVCARIB_VIEWS_LIB_DIR)\
	       $(DEVCARIB_VIEWS_MIA_LESS_IMPORTS)\
	       $(DEVCARIB_VIEWS_MIA_CSS_FILE)\
	       $(DEVCARIB_VIEWS_CONVERSE_LESS_IMPORTS)\
	       $(DEVCARIB_VIEWS_CONVERSE_CSS_FILE)
