import * as _json from '@quenk/noni/lib/data/jsonx';
/**
 * MailMessage type (AUTOGENERATED).
 */
export interface MailMessage extends _json.Object {
    [key: string]: _json.Value;
    'id'?: string;
    'to'?: string;
    'from'?: string;
    'body'?: string;
}
