/** 
 * AUTOGENERATED DO NOT EDIT DIRECTLY!
 */
import { Record } from '@quenk/noni/lib/data/record';

import { EnabledPolicies } from '@quenk/search-filters-mongodb';

export { EnabledPolicies }

import _admin from './admin';
import _event from './event';
import _invite from './invite';
import _job from './job';
import _user from './user';

/**
 * policiesAvailable is a map of model names to search filter policies that can
 * be used in an application.
 */
export const policiesAvailable: Record<EnabledPolicies> = {

    'admin': _admin,

    'event': _event,

    'invite': _invite,

    'job': _job,

    'user': _user
}

