/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
import { Admin } from '@mia/types/lib/admin';
import * as mongodb from 'mongodb';
import { BaseModel } from '@quenk/backend/lib/app/db/mongodb/model';


export {
  AdminModel as ModelImpl,
  Admin as DataType
}

/**
 * AdminModelModel for Admin (AUTOGENERATED).
 */
export class AdminModel extends BaseModel<Admin> {

  constructor(
    public name: string,
    public database: mongodb.Db,
    public collection : mongodb.Collection) { super(database, collection); }

    id = 'id';

  static getInstance (db: mongodb.Db) : AdminModel {

    return new AdminModel('admins', db, db.collection('admins'));

  }

}
