/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
import { Event } from '@mia/types/lib/event';
import * as mongodb from 'mongodb';
import { BaseModel } from '@quenk/backend/lib/app/db/mongodb/model';


export {
  EventModel as ModelImpl,
  Event as DataType
}

/**
 * EventModelModel for Event (AUTOGENERATED).
 */
export class EventModel extends BaseModel<Event> {

  constructor(
    public name: string,
    public database: mongodb.Db,
    public collection : mongodb.Collection) { super(database, collection); }

    id = 'id';

  static getInstance (db: mongodb.Db) : EventModel {

    return new EventModel('events', db, db.collection('events'));

  }

}
