/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
import { Invite } from '@mia/types/lib/invite';
import * as mongodb from 'mongodb';
import { BaseModel } from '@quenk/backend/lib/app/db/mongodb/model';


export {
  InviteModel as ModelImpl,
  Invite as DataType
}

/**
 * InviteModelModel for Invite (AUTOGENERATED).
 */
export class InviteModel extends BaseModel<Invite> {

  constructor(
    public name: string,
    public database: mongodb.Db,
    public collection : mongodb.Collection) { super(database, collection); }

    id = 'id';

  static getInstance (db: mongodb.Db) : InviteModel {

    return new InviteModel('invites', db, db.collection('invites'));

  }

}
