/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
import { Job } from '@board/types/lib/job';
import * as _json from '@quenk/noni/lib/data/jsonx';
import * as _prec from '@quenk/preconditions/lib/async';
/**
 * DataType checked.
 *
 * Used by template generation.
 * @private
 */
export type DataType = Job;
/**
 * fieldChecks for Job (AUTOGENERATED).
 */
export declare const fieldChecks: _prec.Preconditions<_json.Value, _json.Value>;
/**
 * partialFieldChecks for Job (AUTOGENERATED).
 */
export declare const partialFieldChecks: _prec.Preconditions<_json.Value, _json.Value>;
/**
 * check a value to determine if it is a correct Job
 * (AUTOGENERATED).
 */
export declare const check: _prec.Precondition<_json.Value, Job>;
/**
 * checkPartial is like check but only checks the fields encountered.
 * (AUTOGENERATED).
 */
export declare const checkPartial: _prec.Precondition<_json.Value, Partial<Job>>;
