MIA_CHECKS_DIR:=$(MIA_PACKAGES_DIR)/mia-checks
MIA_CHECKS_LIB_DIR:=$(MIA_CHECKS_DIR)/lib
MIA_CHECKS_SRC_DIR:=$(MIA_CHECKS_DIR)/src
MIA_CHECKS_SRC_DIR_FILES:=$(shell find $(MIA_CHECKS_SRC_DIR) -type f)

# Directory with dagen templates.
MIA_CHECKS_TEMPLATE_DIR:=$(MIA_CHECKS_DIR)/templates
MIA_CHECKS_TEMPLATE_DIR_FILES:=$(shell find $(MIA_CHECKS_TEMPLATE_DIR)\
                                     -type f)
MIA_CHECKS_TYPE_TEMPLATE:=type.checks
MIA_CHECKS_INDEX_TEMPLATE:=index.checks

MIA_CHECKS_MODEL_FILES=$(wildcard $(MIA_SCHEMA_MODELS_DIR)/*.json)
MIA_CHECKS_MODEL_FILES_NAMES=$(notdir $(basename \
					$(MIA_CHECKS_MODEL_FILES)))

CLEAN_TARGETS:=$(CLEAN_TARGETS) $(MIA_CHECKS_LIB_DIR)

SRC_DIRS:=$(SRC_DIRS)\
          $(MIA_CHECKS_SRC_DIR)\
	  $(MIA_CHECKS_TEMPLATE_DIR)
