/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
import { Job } from '@board/types/lib/job';
import * as mongodb from 'mongodb';
import { BaseModel } from '@quenk/dback-model-mongodb';
export { JobModel as ModelImpl, Job as DataType };
/**
 * JobModelModel for Job (AUTOGENERATED).
 */
export declare class JobModel extends BaseModel<Job> {
    name: string;
    database: mongodb.Db;
    collection: mongodb.Collection;
    constructor(name: string, database: mongodb.Db, collection: mongodb.Collection);
    id: string;
    static getInstance(db: mongodb.Db): JobModel;
}
