/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
import { MailMessage } from '@board/types/lib/mail-message';
import * as mongodb from 'mongodb';
import { BaseModel } from '@quenk/dback-model-mongodb';
export { MailMessageModel as ModelImpl, MailMessage as DataType };
/**
 * MailMessageModelModel for MailMessage (AUTOGENERATED).
 */
export declare class MailMessageModel extends BaseModel<MailMessage> {
    name: string;
    database: mongodb.Db;
    collection: mongodb.Collection;
    constructor(name: string, database: mongodb.Db, collection: mongodb.Collection);
    id: string;
    static getInstance(db: mongodb.Db): MailMessageModel;
}
