BOARD_TYPES_DIR:=$(PACKAGES_LIBS_DIR)/board-types
BOARD_TYPES_LIB_DIR:=$(BOARD_TYPES_DIR)/lib
BOARD_TYPES_SRC_DIR:=$(BOARD_TYPES_DIR)/src
BOARD_TYPES_SRC_DIR_FILES:=$(shell find $(BOARD_TYPES_SRC_DIR) -type f)

BOARD_TYPES_TYPE_TEMPLATE:=type.types
BOARD_TYPES_TEMPLATE_DIR:=$(BOARD_TYPES_DIR)/templates
BOARD_TYPES_TEMPLATE_DIR_FILES:=$(shell find $(BOARD_TYPES_TEMPLATE_DIR) -type f)

BOARD_TYPES_MODEL_NAMES=$(notdir $(basename $(wildcard \
			$(BOARD_SCHEMA_MODELS_DIR)/*.json)))
BOARD_TYPES_TYPE_NAMES=$(notdir $(basename $(wildcard \
			$(BOARD_SCHEMA_TYPES_DIR)/*.json))) 

CLEAN_TARGETS:=$(CLEAN_TARGETS) $(BOARD_TYPES_LIB_DIR)
