DEVCARIB_SERVER_DIR:=$(PACKAGES_DIR)/devcarib-server
DEVCARIB_SERVER_SRC_DIR:=$(DEVCARIB_SERVER_DIR)/src

DEVCARIB_SERVER_SRC_FILES:=$(shell find $(DEVCARIB_SERVER_SRC_DIR)\
                         -name \*.ts -o -name \*.json)

DEVCARIB_SERVER_LIB_DIR:=$(DEVCARIB_SERVER_DIR)/lib

CLEAN_TARGETS:=$(CLEAN_TARGETS) $(DEVCARIB_SERVER_LIB_DIR)
