/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
 
import { MailMessage } from '@board/types/lib/mail-message';
import { validate,validatePartial } from '../validators/mail-message';
import * as _json from '@quenk/noni/lib/data/jsonx';
import * as _prec from '@quenk/preconditions/lib/async';
import * as _recordPrec from '@quenk/preconditions/lib/async/record';
import * as _arrayPrec from '@quenk/preconditions/lib/async/array';

//@ts-ignore: 6133
const title = "MailMessage";
//@ts-ignore: 6133
const collection = "mail";

/**
 * DataType checked.
 * 
 * Used by template generation.
 * @private 
 */
export type DataType = MailMessage;

/**
 * fieldChecks for MailMessage (AUTOGENERATED).
 */ 
export const fieldChecks: _prec.Preconditions<_json.Value, _json.Value> = {

    'id':                _prec.identity
,

    'to': _prec.identity,

    'from': _prec.identity,

    'body': _prec.identity
};

/**
 * partialFieldChecks for MailMessage (AUTOGENERATED).
 */ 
export const partialFieldChecks: _prec.Preconditions<_json.Value, _json.Value> = {

    'id':                 _prec.identity
,
    'to': _prec.identity,
    'from': _prec.identity,
    'body': _prec.identity};

/**
 * check a value to determine if it is a correct MailMessage
 * (AUTOGENERATED).
 */
export const check: _prec.Precondition<_json.Value, MailMessage> = 
    _prec.and<_json.Value, MailMessage,MailMessage>(
      _prec.async<_json.Value, MailMessage>(validate),
       _recordPrec.restrict(fieldChecks));

/**
 * checkPartial is like check but only checks the fields encountered.
 * (AUTOGENERATED).
 */
 export const checkPartial: _prec.Precondition<_json.Value, Partial<MailMessage>> = 
    _prec.and<_json.Value, MailMessage,MailMessage>(_prec.async<_json.Value,MailMessage>(validatePartial), 
   _recordPrec.intersect(partialFieldChecks));  
