/**
 * AUTOGENERATED, DO NOT EDIT DIRECTLY!
 */

import { Admin } from '@mia/types/lib/admin';
import * as remoteModel from '@quenk/jouvert/lib/app/remote/model';

/**
 * AdminRemoteModel remote model (AUTOGENERATED).
 */
export class AdminRemoteModel 
  extends 
  remoteModel.RemoteModel<Admin> {

  static paths = {"search":"/mia/r/admins","get":"/mia/r/admins/{id}"}

  requests = new remoteModel.RequestFactory(AdminRemoteModel.paths);

}
