/**
 * AUTOGENERATED, DO NOT EDIT DIRECTLY!
 */

import { Event } from '@mia/types/lib/event';
import * as remoteModel from '@quenk/jouvert/lib/app/remote/model';

/**
 * EventRemoteModel remote model (AUTOGENERATED).
 */
export class EventRemoteModel 
  extends 
  remoteModel.RemoteModel<Event> {

  static paths = {"search":"/mia/r/events","get":"/mia/r/events/{id}"}

  requests = new remoteModel.RequestFactory(EventRemoteModel.paths);

}
