/**
 * AUTOGENERATED, DO NOT EDIT DIRECTLY!
 */

import { Invite } from '@mia/types/lib/invite';
import * as remoteModel from '@quenk/jouvert/lib/app/remote/model';

/**
 * InviteRemoteModel remote model (AUTOGENERATED).
 */
export class InviteRemoteModel 
  extends 
  remoteModel.RemoteModel<Invite> {

  static paths = {"search":"/mia/r/invites","get":"/mia/r/invites/{id}"}

  requests = new remoteModel.RequestFactory(InviteRemoteModel.paths);

}
