/**
 * AUTOGENERATED, DO NOT EDIT DIRECTLY!
 */

import { Job } from '@mia/types/lib/job';
import * as remoteModel from '@quenk/jouvert/lib/app/remote/model';

/**
 * JobRemoteModel remote model (AUTOGENERATED).
 */
export class JobRemoteModel 
  extends 
  remoteModel.RemoteModel<Job> {

  static paths = {"search":"/mia/r/jobs","get":"/mia/r/jobs/{id}"}

  requests = new remoteModel.RequestFactory(JobRemoteModel.paths);

}
