/**
 * AUTOGENERATED, DO NOT EDIT DIRECTLY!
 */

import { User } from '@mia/types/lib/user';
import * as remoteModel from '@quenk/jouvert/lib/app/remote/model';

/**
 * UserRemoteModel remote model (AUTOGENERATED).
 */
export class UserRemoteModel 
  extends 
  remoteModel.RemoteModel<User> {

  static paths = {"search":"/mia/r/users","get":"/mia/r/users/{id}"}

  requests = new remoteModel.RequestFactory(UserRemoteModel.paths);

}
