MIA_REMOTE_MODELS_DIR:=$(MIA_FRONTEND_SRC_DIR)/app/remote/models
MIA_REMOTE_MODELS_FILES=$(addsuffix .ts,$(addprefix $(MIA_REMOTE_MODELS_DIR)/,\
			$(MIA_SCHEMA_MODEL_NAMES)))
CLEAN_TARGETS:=$(CLEAN_TARGETS) $(MIA_REMOTE_MODELS_DIR)/*.ts
