CONVERSE_FRONTEND_DIR:=$(CONVERSE_DIR)/frontend
CONVERSE_FRONTEND_JS_VARS:=$(HERE)/node_modules/@quenk/wml-widgets/lib/classNames.js
CONVERSE_FRONTEND_SRC_DIR:=$(CONVERSE_FRONTEND_DIR)/src

CONVERSE_FRONTEND_SRC_FILES:=$(shell find $(CONVERSE_FRONTEND_SRC_DIR) -type f)

CONVERSE_FRONTEND_LIB_DIR:=$(CONVERSE_FRONTEND_DIR)/lib
CONVERSE_FRONTEND_LESS_FILES:=$(shell find $(CONVERSE_FRONTEND_SRC_DIR)\
                                -name \*.less)
CONVERSE_FRONTEND_LESS_MAIN:=$(CONVERSE_FRONTEND_DIR)/main.less
CONVERSE_FRONTEND_LESS_IMPORTS:=$(CONVERSE_FRONTEND_DIR)/imports.less
CONVERSE_FRONTEND_PUBLIC_DIR:=$(CONVERSE_FRONTEND_DIR)/public
CONVERSE_FRONTEND_JS_FILE:=$(CONVERSE_FRONTEND_PUBLIC_DIR)/converse/assets/js/converse.js
CONVERSE_FRONTEND_CSS_FILE:=$(CONVERSE_FRONTEND_PUBLIC_DIR)/converse/assets/css/converse.css

CLEAN_TARGETS:=$(CLEAN_TARGETS)\
               $(CONVERSE_FRONTEND_PUBLIC_DIR)\
               $(CONVERSE_FRONTEND_LIB_DIR)

CONVERSE_FRONTEND_FRONTEND_TEST_DIR:=$(CONVERSE_FRONTEND_DIR)/test/frontend
CONVERSE_FRONTEND_FRONTEND_TEST_SRC_DIR:=$(CONVERSE_FRONTEND_FRONTEND_TEST_DIR)/src

CONVERSE_FRONTEND_FRONTEND_TEST_SRC_DIR_FILES:=$(shell find\
  $(CONVERSE_FRONTEND_FRONTEND_TEST_SRC_DIR) -name \*_test.ts)

CONVERSE_FRONTEND_FRONTEND_TEST_BUILD_DIR:=$(CONVERSE_FRONTEND_FRONTEND_TEST_DIR)/build
CONVERSE_FRONTEND_FRONTEND_TEST_BUNDLE_DIR:=$(CONVERSE_FRONTEND_FRONTEND_TEST_DIR)/bundle

include $(CONVERSE_FRONTEND_SRC_DIR)/app/remote/models/variables.mk
