CONVERSE_FRONTEND_DIR:=$(CONVERSE_DIR)/frontend
CONVERSE_FRONTEND_SRC_DIR:=$(CONVERSE_FRONTEND_DIR)/src

CONVERSE_FRONTEND_SRC_FILES:=$(shell find $(CONVERSE_FRONTEND_SRC_DIR)\
                         -name \*.ts -o -name \*.json -o -name \*.wml)

CONVERSE_FRONTEND_LIB_DIR:=$(CONVERSE_FRONTEND_DIR)/lib
CONVERSE_FRONTEND_LESS_FILES:=$(shell find $(CONVERSE_FRONTEND_SRC_DIR)\
                                -name \*.less)
CONVERSE_FRONTEND_LESS_MAIN:=$(CONVERSE_FRONTEND_DIR)/main.less
CONVERSE_FRONTEND_LESS_IMPORTS:=$(CONVERSE_FRONTEND_DIR)/imports.less
CONVERSE_FRONTEND_PUBLIC_DIR:=$(CONVERSE_FRONTEND_DIR)/public
CONVERSE_FRONTEND_JS_FILE:=$(CONVERSE_FRONTEND_PUBLIC_DIR)/converse/assets/js/app.js
CONVERSE_FRONTEND_CSS_FILE:=$(CONVERSE_FRONTEND_PUBLIC_DIR)/converse/assets/css/app.css

include $(CONVERSE_FRONTEND_SRC_DIR)/app/remote/models/variables.mk

CLEAN_TARGETS:=$(CLEAN_TARGETS)\
               $(CONVERSE_FRONTEND_PUBLIC_DIR)\
               $(CONVERSE_FRONTEND_LIB_DIR)
