CONVERSE_CHECKS_DIR:=$(CONVERSE_LIBS_DIR)/converse-checks
CONVERSE_CHECKS_LIB_DIR:=$(CONVERSE_CHECKS_DIR)/lib
CONVERSE_CHECKS_SRC_DIR:=$(CONVERSE_CHECKS_DIR)/src
CONVERSE_CHECKS_SRC_DIR_FILES:=$(shell find $(CONVERSE_CHECKS_SRC_DIR) -type f)

# Directory with dagen templates.
CONVERSE_CHECKS_TEMPLATE_DIR:=$(CONVERSE_CHECKS_DIR)/templates
CONVERSE_CHECKS_TEMPLATE_DIR_FILES:=$(shell find $(CONVERSE_CHECKS_TEMPLATE_DIR)\
                                     -type f)
CONVERSE_CHECKS_TYPE_TEMPLATE:=type.checks
CONVERSE_CHECKS_INDEX_TEMPLATE:=index.checks

CONVERSE_CHECKS_MODEL_FILES=$(wildcard $(CONVERSE_SCHEMA_MODELS_DIR)/*.json)
CONVERSE_CHECKS_MODEL_FILES_NAMES=$(notdir $(basename \
					$(CONVERSE_CHECKS_MODEL_FILES)))

# Hook into clean task.
CLEAN_TARGETS:=$(CLEAN_TARGETS) $(CONVERSE_CHECKS_LIB_DIR)

# Add our sources to the list of total project sources.
SRC_DIRS:=$(SRC_DIRS)\
          $(CONVERSE_CHECKS_SRC_DIR)\
          $(CONVERSE_CHECKS_TEMPLATE_DIR)
