# Requires:
# 1. MIA_FILTER_POLICIES_DIR
# 2. MIA_SCHEMA_MODELS_DIR

MIA_FILTER_POLICIES_DIR:=$(MIA_PACKAGES_DIR)/mia-filter-policies
MIA_FILTER_POLICIES_LIB_DIR:=$(MIA_FILTER_POLICIES_DIR)/lib
MIA_FILTER_POLICIES_SRC_DIR:=$(MIA_FILTER_POLICIES_DIR)/src
MIA_FILTER_POLICIES_TEMPLATES_DIR:=$(MIA_FILTER_POLICIES_DIR)/templates

MIA_FILTER_POLICIES_TEMPLATE_FILES:=\
                      $(shell find $(MIA_FILTER_POLICIES_TEMPLATES_DIR) -type f)

MIA_FILTER_POLICIES_SRC_DIR_FILES:=\
                      $(shell find $(MIA_FILTER_POLICIES_SRC_DIR) -type f)

MIA_FILTER_POLICIES_MODEL_FILES=$(wildcard $(MIA_SCHEMA_MODELS_DIR)/*.json)

MIA_FIELDS_MODEL_NAMES=$(notdir $(basename $(wildcard \
			   $(MIA_SCHEMA_MODELS_DIR)/*.json)))
