$(DEVCARIB_COMMON_CHECKS_DIR): $(DEVCARIB_COMMON_CHECKS_LIB_DIR)\
	                       $(DEVCARIB_COMMON_VALIDATORS_DIR)
	touch $@

$(DEVCARIB_COMMON_CHECKS_LIB_DIR): $(DEVCARIB_COMMON_CHECKS_SRC_DIR)
	rm -R $@ 2> /dev/null || true 
	mkdir -p  $@
	cp -R -u $(DEVCARIB_COMMON_CHECKS_SRC_DIR)/* $@
	$(TSC) --project $@
	touch $@

$(DEVCARIB_COMMON_CHECKS_SRC_DIR): $(DEVCARIB_COMMON_CHECKS_SRC_DIR_FILES)
	touch $@
