DEVCARIB_COMMON_DIR:=$(PACKAGES_DIR)/devcarib-common
DEVCARIB_COMMON_SRC_DIR:=$(DEVCARIB_COMMON_DIR)/src

DEVCARIB_COMMON_SRC_FILES:=$(shell find $(DEVCARIB_COMMON_SRC_DIR)\
                         -name \*.ts -o -name \*.json)

DEVCARIB_COMMON_LIB_DIR:=$(DEVCARIB_COMMON_DIR)/lib

CLEAN_TARGETS:=$(CLEAN_TARGETS) $(DEVCARIB_COMMON_LIB_DIR)
