CONVERSE_DIR:=$(APPS_DIR)/converse
CONVERSE_SRC_DIR:=$(CONVERSE_DIR)/src
CONVERSE_SRC_DIR_FILES:=$(shell find $(CONVERSE_SRC_DIR) -type f)
CONVERSE_BUILD_DIR:=$(CONVERSE_DIR)/build
CONVERSE_PACKAGES_DIR:=$(CONVERSE_DIR)/packages
CONVERSE_FRONTEND_DIR:=$(CONVERSE_DIR)/frontend

include $(CONVERSE_DIR)/schema/variables.mk
include $(CONVERSE_PACKAGES_DIR)/*/variables.mk
include $(CONVERSE_FRONTEND_DIR)/variables.mk

CONVERSE_PUBLIC_DIR:=$(CONVERSE_DIR)/public/converse
CONVERSE_CSS_FILE:=$(CONVERSE_PUBLIC_DIR)/assets/css/site.css
CONVERSE_LESS_FILES:=$(shell find $(CONVERSE_SRC_DIR) -name \*.less)
CONVERSE_LESS_MAIN_FILE:=$(CONVERSE_DIR)/main.less
CONVERSE_LESS_IMPORTS_FILE:=$(CONVERSE_DIR)/imports.less
