CONVERSE_DIR:=$(DC_APPS_DIR)/converse
CONVERSE_SCHEMA_DIR:=$(CONVERSE_DIR)/schema
CONVERSE_PACKAGES_DIR:=$(CONVERSE_DIR)/packages
CONVERSE_BUILD_DIR:=$(CONVERSE_DIR)/build
CONVERSE_FRONTEND_DIR:=$(CONVERSE_DIR)/frontend
CONVERSE_PUBLIC_DIR:=$(CONVERSE_DIR)/public

CLEAN_TARGETS:=$(CLEAN_TARGETS) \
	        $(CONVERSE_BUILD_DIR) \
	        $(CONVERSE_PUBLIC_DIR)/assets/css/converse.css

include $(CONVERSE_SCHEMA_DIR)/variables.mk
include $(CONVERSE_PACKAGES_DIR)/*/variables.mk
include $(CONVERSE_FRONTEND_DIR)/variables.mk
