DEVCARIB_COMMON_VALIDATORS_DIR:=$(PACKAGES_LIBS_DIR)/devcarib-common-validators
DEVCARIB_COMMON_VALIDATORS_SRC_DIR:=$(DEVCARIB_COMMON_VALIDATORS_DIR)/src
DEVCARIB_COMMON_VALIDATORS_SRC_DIR_FILES:=$(shell find $(DEVCARIB_COMMON_VALIDATORS_SRC_DIR) -type f)
DEVCARIB_COMMON_VALIDATORS_LIB_DIR:=$(DEVCARIB_COMMON_VALIDATORS_DIR)/lib

# Hook into clean task.
CLEAN_TARGETS:=$(CLEAN_TARGETS) $(DEVCARIB_COMMON_VALIDATORS_LIB_DIR)

# Add our sources to the list of total project sources.
SRC_DIRS:=$(SRC_DIRS) $(DEVCARIB_COMMON_VALIDATORS_SRC_DIR)
