DEVCARIB_FRONTEND_DIR:=$(PACKAGES_DIR)/devcarib-frontend
DEVCARIB_FRONTEND_SRC_DIR:=$(DEVCARIB_FRONTEND_DIR)/src

DEVCARIB_FRONTEND_SRC_FILES:=$(shell find $(DEVCARIB_FRONTEND_SRC_DIR)\
                         -name \*.ts -o -name \*.json)

DEVCARIB_FRONTEND_LIB_DIR:=$(DEVCARIB_FRONTEND_DIR)/lib

CLEAN_TARGETS:=$(CLEAN_TARGETS) $(DEVCARIB_FRONTEND_LIB_DIR)
