BOARD_LIBS_DIR:=$(PACKAGES_DIR)/libs

BOARD_TYPES_DIR:=$(BOARD_LIBS_DIR)/board-types
BOARD_COMMON_DIR:=$(BOARD_LIBS_DIR)/board-common
BOARD_VALIDATORS_DIR:=$(BOARD_LIBS_DIR)/board-validators
BOARD_CHECKS_DIR:=$(BOARD_LIBS_DIR)/board-checks
BOARD_WIDGETS_DIR:=$(BOARD_LIBS_DIR)/board-widgets
BOARD_VIEWS_DIR:=$(BOARD_LIBS_DIR)/board-views
