/**
 *AUTOGENERATED, DO NOT EDIT DIRECTLY.
 */
import { Record } from '@quenk/noni/lib/data/record';
/**
 * Fields for mongodb projection.
 */
export interface Fields extends Record<number> {
}
/**
 * fieldsAvailable from this module.
 */
export declare const fieldsAvailable: Record<Fields>;
