/**
 *AUTOGENERATED, DO NOT EDIT DIRECTLY. 
 */
import { Record } from '@quenk/noni/lib/data/record';

import _job from './job';
import _mailMessage from './mail-message';

/**
 * Fields for mongodb projection.
 */
export interface Fields extends Record<number> {}

/**
 * fieldsAvailable from this module.
 */
export const fieldsAvailable: Record<Fields> = {


    'job': _job,

    'mailMessage': _mailMessage

}

