/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
 
import { Admin } from '@mia/types/lib/admin';
import { validate,validatePartial } from '../validators/admin';
import { bcrypt,inc,unique } from '@devcarib/server/lib/data/checks';
import * as _json from '@quenk/noni/lib/data/jsonx';
import * as _prec from '@quenk/preconditions/lib/async';
import * as _recordPrec from '@quenk/preconditions/lib/async/record';
import * as _arrayPrec from '@quenk/preconditions/lib/async/array';

//@ts-ignore: 6133
const title = "Admin";
//@ts-ignore: 6133
const collection = "admins";

//@ts-ignore: 6133
const _complete = _recordPrec.restrict;

//@ts-ignore: 6133
const _partial = _recordPrec.intersect;

/**
 * DataType checked.
 * 
 * Used by template generation.
 * @private 
 */
export type DataType = Admin;

/**
 * fieldChecks for Admin (AUTOGENERATED).
 */ 
export const fieldChecks: _prec.Preconditions<_json.Value, _json.Value> = {

    'id': _prec.every<_json.Value,_json.Value>(unique('admins','id')),

    'name': _prec.identity,

    'email': _prec.identity,

    'password': _prec.every<_json.Value,_json.Value>(bcrypt)
};

/**
 * partialFieldChecks for Admin (AUTOGENERATED).
 */ 
export const partialFieldChecks: _prec.Preconditions<_json.Value, _json.Value> = {

    'id':                 _prec.identity
,
    'name': _prec.identity,
    'email': _prec.identity,
    'password': _prec.every<_json.Value,_json.Value>(bcrypt)};

/**
 * check a value to determine if it is a correct Admin
 * (AUTOGENERATED).
 */
export const check: _prec.Precondition<_json.Value, Admin> = 
    _prec.and(_prec.and<_json.Value, Admin,Admin>(
      _prec.async(validate), _recordPrec.restrict(fieldChecks)),
      _prec.every<Admin,Admin>(inc('admins'))
     );

/**
 * checkPartial is like check but only checks the fields encountered.
 * (AUTOGENERATED).
 */
 export const checkPartial: _prec.Precondition<_json.Value, Partial<Admin>> = 
    _prec.and<_json.Value, Admin,Admin>(_prec.async<_json.Value,Admin>(validatePartial), 
   _recordPrec.intersect(partialFieldChecks));  
