/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */ 
import * as _admin from './admin';
import * as _event from './event';
import * as _invite from './invite';
import * as _job from './job';
import * as _user from './user';

import { Value } from '@quenk/noni/lib/data/jsonx';
import { Maybe, fromNullable} from '@quenk/noni/lib/data/maybe';
import { Record } from '@quenk/noni/lib/data/record';
import { Precondition } from '@quenk/preconditions/lib/async';

/**
 * DataTypeUnion combines all the checks data types found in this module
 * (AUTOGENERATED).
 */
export type DataTypeUnion =
  
    _admin.DataType |
  
    _event.DataType |
  
    _invite.DataType |
  
    _job.DataType |
  
    _user.DataType ;

/**
 * ChecksMap is a record mapping normalized model names to their respective 
 * checks.
 */
export interface ChecksMap 
  extends 
  Record<Precondition<Value, DataTypeUnion>>{}

/**
 * checksAvailable from this module (AUTOGENERATED).
 */
export const checksAvailable: ChecksMap = {

    
    'admin': <Precondition<Value, DataTypeUnion>>_admin.check,
    
    'event': <Precondition<Value, DataTypeUnion>>_event.check,
    
    'invite': <Precondition<Value, DataTypeUnion>>_invite.check,
    
    'job': <Precondition<Value, DataTypeUnion>>_job.check,
    
    'user': <Precondition<Value, DataTypeUnion>>_user.check

};

/**
 * getChecksFor provides a validator from this module.
 */
export const getChecksFor = 
 (name:string) : Maybe<Precondition<Value, DataTypeUnion>> => 
 fromNullable(checksAvailable[name]);

/**
 * partialChecksAvailable from this module.
 */
export const partialChecksAvailable: ChecksMap = {


    'admin': <Precondition<Value, Partial<DataTypeUnion>>>_admin.checkPartial,

    'event': <Precondition<Value, Partial<DataTypeUnion>>>_event.checkPartial,

    'invite': <Precondition<Value, Partial<DataTypeUnion>>>_invite.checkPartial,

    'job': <Precondition<Value, Partial<DataTypeUnion>>>_job.checkPartial,

    'user': <Precondition<Value, Partial<DataTypeUnion>>>_user.checkPartial
};

/**
 * getPartialChecksFor provides a validator from this module.
 */
export const getPartialChecksFor = 
(name:string) : Maybe<Precondition<Value, DataTypeUnion>> => 
 fromNullable(partialChecksAvailable[name]);

