/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
 
import { Job } from '@mia/types/lib/job';
import { validate,validatePartial } from '../validators/job';
import { parseMarkdown,inc,unique } from '@devcarib/server/lib/data/checks';
import * as _json from '@quenk/noni/lib/data/jsonx';
import * as _prec from '@quenk/preconditions/lib/async';
import * as _recordPrec from '@quenk/preconditions/lib/async/record';
import * as _arrayPrec from '@quenk/preconditions/lib/async/array';

//@ts-ignore: 6133
const title = "Job";
//@ts-ignore: 6133
const collection = "jobs";

//@ts-ignore: 6133
const _complete = _recordPrec.restrict;

//@ts-ignore: 6133
const _partial = _recordPrec.intersect;

/**
 * DataType checked.
 * 
 * Used by template generation.
 * @private 
 */
export type DataType = Job;

/**
 * fieldChecks for Job (AUTOGENERATED).
 */ 
export const fieldChecks: _prec.Preconditions<_json.Value, _json.Value> = {

    'id': _prec.every<_json.Value,_json.Value>(unique('jobs','id')),

    'title': _prec.identity,

    'type': _prec.identity,

    'location': _prec.identity,

    'remote': _prec.identity,

    'description': _prec.identity,

    'description_html':                _prec.identity
,

    'company': _prec.identity,

    'company_email': _prec.identity,

    'company_logo': _prec.identity,

    'apply_url': _prec.identity,

    'approved': _prec.identity,

    'payment_currency': _prec.identity,

    'payment_amount': _prec.identity,

    'payment_frequency': _prec.identity,

    'status': _prec.identity,

    'created_by':                _prec.identity
,

    'created_on':                _prec.identity
,

    'last_updated_on':                _prec.identity
,

    'last_updated_by':                _prec.identity

};

/**
 * partialFieldChecks for Job (AUTOGENERATED).
 */ 
export const partialFieldChecks: _prec.Preconditions<_json.Value, _json.Value> = {

    'id':                 _prec.identity
,
    'title': _prec.identity,
    'type': _prec.identity,
    'location': _prec.identity,
    'remote': _prec.identity,
    'description': _prec.identity,
    'description_html':                 _prec.identity
,
    'company': _prec.identity,
    'company_email': _prec.identity,
    'company_logo': _prec.identity,
    'apply_url': _prec.identity,
    'approved': _prec.identity,
    'payment_currency': _prec.identity,
    'payment_amount': _prec.identity,
    'payment_frequency': _prec.identity,
    'status': _prec.identity,
    'created_by':                 _prec.identity
,
    'created_on':                 _prec.identity
,
    'last_updated_on':                 _prec.identity
,
    'last_updated_by':                 _prec.identity
};

/**
 * check a value to determine if it is a correct Job
 * (AUTOGENERATED).
 */
export const check: _prec.Precondition<_json.Value, Job> = 
    _prec.and(_prec.and<_json.Value, Job,Job>(
      _prec.async(validate), _recordPrec.restrict(fieldChecks)),
      _prec.every<Job,Job>(parseMarkdown('description','description_html',true),inc('jobs'))
     );

/**
 * checkPartial is like check but only checks the fields encountered.
 * (AUTOGENERATED).
 */
 export const checkPartial: _prec.Precondition<_json.Value, Partial<Job>> = 
    _prec.and(_prec.and<_json.Value, Job,Job>(
      _prec.async(validatePartial),
      _recordPrec.intersect(partialFieldChecks)),
    _prec.every(parseMarkdown('description','description_html',true)));
