/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
 
import { User } from '@mia/types/lib/user';
import { validate,validatePartial } from '../validators/user';
import { inc,unique,bcrypt } from '@devcarib/server/lib/data/checks';
import * as _json from '@quenk/noni/lib/data/jsonx';
import * as _prec from '@quenk/preconditions/lib/async';
import * as _recordPrec from '@quenk/preconditions/lib/async/record';
import * as _arrayPrec from '@quenk/preconditions/lib/async/array';

//@ts-ignore: 6133
const title = "User";
//@ts-ignore: 6133
const collection = "users";

//@ts-ignore: 6133
const _complete = _recordPrec.restrict;

//@ts-ignore: 6133
const _partial = _recordPrec.intersect;

/**
 * DataType checked.
 * 
 * Used by template generation.
 * @private 
 */
export type DataType = User;

/**
 * fieldChecks for User (AUTOGENERATED).
 */ 
export const fieldChecks: _prec.Preconditions<_json.Value, _json.Value> = {

    'id': _prec.every<_json.Value,_json.Value>(unique(collection,'id')),

    'name': _prec.identity,

    'username': _prec.every<_json.Value,_json.Value>(unique(collection,'username')),

    'password': _prec.every<_json.Value,_json.Value>(bcrypt),

    'status': _prec.identity,

    'last_login':                _prec.identity

};

/**
 * partialFieldChecks for User (AUTOGENERATED).
 */ 
export const partialFieldChecks: _prec.Preconditions<_json.Value, _json.Value> = {

    'id': _prec.every<_json.Value,_json.Value>(unique(collection,'id')),
    'name': _prec.identity,
    'username': _prec.every<_json.Value,_json.Value>(unique(collection,'username')),
    'password': _prec.every<_json.Value,_json.Value>(bcrypt),
    'status': _prec.identity,
    'last_login':                 _prec.identity
};

/**
 * check a value to determine if it is a correct User
 * (AUTOGENERATED).
 */
export const check: _prec.Precondition<_json.Value, User> = 
    _prec.and(_prec.and<_json.Value, User,User>(
      _prec.async(validate), _recordPrec.restrict(fieldChecks)),
      _prec.every<User,User>(inc('users'))
     );

/**
 * checkPartial is like check but only checks the fields encountered.
 * (AUTOGENERATED).
 */
 export const checkPartial: _prec.Precondition<_json.Value, Partial<User>> = 
    _prec.and(_prec.and<_json.Value, User,User>(
      _prec.async(validatePartial),
      _recordPrec.intersect(partialFieldChecks)),
    _prec.every(inc('users')));
