
MIA_VALIDATORS_DIR:=$(MIA_PACKAGES_DIR)/mia-validators
MIA_VALIDATORS_PLUGIN?=node_modules/@quenk/dagen-commons/lib/plugins/validation
MIA_VALIDATORS_SRC_DIR:=$(MIA_VALIDATORS_DIR)/src
MIA_VALIDATORS_SRC_DIR_FILES:=$(shell find $(MIA_VALIDATORS_SRC_DIR) -type f)
MIA_VALIDATORS_LIB_DIR:=$(MIA_VALIDATORS_DIR)/lib

MIA_VALIDATORS_TEMPLATE_DIR:=$(MIA_VALIDATORS_DIR)/templates
MIA_VALIDATORS_TEMPLATE_DIR_FILES:=$(shell find \
				    $(MIA_VALIDATORS_TEMPLATE_DIR) -type f)
MIA_VALIDATORS_TYPE_TEMPLATE:=type.validators
MIA_VALIDATORS_INDEX_TEMPLATE:=index.validators

MIA_VALIDATORS_MODEL_FILES=$(wildcard $(MIA_SCHEMA_MODELS_DIR)/*.json)
MIA_VALIDATORS_TYPES_FILES=$(wildcard $(MIA_SCHEMA_TYPES_DIR)/*.json)
MIA_VALIDATORS_SRC_FILES=$(MIA_VALIDATORS_MODEL_FILES) \
			  $(MIA_VALIDATORS_TYPES_FILES)
MIA_VALIDATORS_SRC_FILES_NAMES=$(notdir $(basename \
				$(MIA_VALIDATORS_MODEL_FILES)))

# Test generation.
MIA_VALIDATORS_TEST_DIR:=$(MIA_VALIDATORS_DIR)/test
MIA_VALIDATORS_UNIT_TEST_DIR:=$(MIA_VALIDATORS_TEST_DIR)/unit
MIA_VALIDATORS_TEST_TEMPLATE:=test.validators
MIA_VALIDATORS_TEST_DATA_DIR:=$(MIA_VALIDATORS_TEST_DIR)/fixtures/data 
MIA_VALIDATORS_EXTRA_TEST_DIR:=$(MIA_VALIDATORS_TEST_DIR)/unitextras

CLEAN_TARGETS:=$(CLEAN_TARGETS)\
               $(MIA_VALIDATORS_LIB_DIR)\
	       $(MIA_VALIDATORS_TEST_DIR)

SRC_DIRS:=$(SRC_DIRS)\
	  $(MIA_VALIDATORS_SRC_DIR)\
	  $(MIA_VALIDATORS_TEST_DATA_DIR)\
	  $(MIA_VALIDATORS_TEMPLATE_DIR)
