/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
import { Job } from '@board/types/lib/job';
import * as _json from '@quenk/noni/lib/data/jsonx';
import * as _prec from '@quenk/preconditions';
/**
 * DataType validated.
 *
 * Used by template generation.
 * @private
 */
export type DataType = Job;
/**
 * fieldValidators for Job (AUTOGENERATED).
 */
export declare const fieldValidators: _prec.Preconditions<_json.Value, _json.Value>;
/**
 * partialFieldValidators for Job (AUTOGENERATED).
 */
export declare const partialFieldValidators: _prec.Preconditions<_json.Value, _json.Value>;
/**
 * validate a value to determine if it satisfies the Job type
 * (AUTOGENERATED).
 */
export declare const validate: _prec.Precondition<_json.Value, Job>;
/**
 * validatePartial is like validate but only tests the fields encountered
 * (AUTOGENERATED).
 */
export declare const validatePartial: _prec.Precondition<_json.Value, Partial<Job>>;
