/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
import { MailMessage } from '@board/types/lib/mail-message';
import * as _json from '@quenk/noni/lib/data/jsonx';
import * as _prec from '@quenk/preconditions';
/**
 * DataType validated.
 *
 * Used by template generation.
 * @private
 */
export type DataType = MailMessage;
/**
 * fieldValidators for MailMessage (AUTOGENERATED).
 */
export declare const fieldValidators: _prec.Preconditions<_json.Value, _json.Value>;
/**
 * partialFieldValidators for MailMessage (AUTOGENERATED).
 */
export declare const partialFieldValidators: _prec.Preconditions<_json.Value, _json.Value>;
/**
 * validate a value to determine if it satisfies the MailMessage type
 * (AUTOGENERATED).
 */
export declare const validate: _prec.Precondition<_json.Value, MailMessage>;
/**
 * validatePartial is like validate but only tests the fields encountered
 * (AUTOGENERATED).
 */
export declare const validatePartial: _prec.Precondition<_json.Value, Partial<MailMessage>>;
